Revert "wallet: ensure wallet files are not reused across chains #18554"
This reverts commit 0ce43abd58195ff326a55a259d405aef2a395b95.
EXCEPTION: St12system_error
Invalid argument
nusacoin in Runaway exception